services:
  postgres:
    image: postgres:15
    container_name: lending_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: platform_demo
    ports:
      - "5432:5432"
    volumes:
      - ../data:/data
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance_platform_network

  dbt:
    platform: linux/amd64
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /usr/app
    volumes:
      - ../:/usr/app
      - ../data:/data
      - ../profiles:/.dbt
    entrypoint: ["dbt"]
    depends_on:
      - postgres
    networks:
      - finance_platform_network

volumes:
  postgres_data:

networks:
  finance_platform_network:
    name: finance_platform_network
