
services:
  superset:
    build: .
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: supersecretkey
      SUPERSET_ADMIN_USERNAME: admin
      SUPERSET_ADMIN_FIRSTNAME: admin
      SUPERSET_ADMIN_LASTNAME: admin
      SUPERSET_ADMIN_EMAIL: admin@superset.com
      SUPERSET_ADMIN_PASSWORD: admin
      SUPERSET_ANALYTICS_DB_NAME: platform_demo
      SUPERSET_ANALYTICS_DB_USER: postgres
      SUPERSET_ANALYTICS_DB_PASSWORD: postgres
      SUPERSET_ANALYTICS_DB_HOST: postgres
      SUPERSET_ANALYTICS_DB_PORT: 5432
    volumes:
      - superset_home:/app/superset_home
      - ./bootstrap.sh:/app/bootstrap/bootstrap.sh:ro
    networks:
      - finance_platform_network
    command:
      - /bin/sh
      - -c
      - |
        /bin/sh /app/bootstrap/bootstrap.sh

volumes:
  superset_home:

networks:
  finance_platform_network:
    external: true
    name: finance_platform_network
